export { default as Navbar} from './Navbar/Navbar.jsx'
export { default as Heading} from './Heading/Heading'
export { default as Middle} from './Middle/Middle'
export { default as Description} from './Description/Description'
export { default as Feature} from './Feature/Feature'
export { default as Footer} from './Footer/Footer'